# This compiles the example(s) and the library

from init_env import init_environment

# load glibraries
env = init_environment("glibrary")
env.Append(CXXFLAGS=['-std=c++17'])

# manually appending this library so the example can be compiled
# the environment above will not load gdigitization if it's not there
env.Append(LIBS = 'gdigitization')

# calling SConscript here to build just the library as in the hierarchy build
lib = SConscript('SConscript', exports='env')

# builds the example(s)
example = env.Program(source = "example.cc", target = "example")

Depends(example,  lib);
