# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')

sources = [
			  'gutilities.cc',
			  'gutsConventions.cc'
			  ]

# destination library is one dir up - relative to this SConscript
lib = env.Library(source = sources, target='../lib/guts')
