#!/bin/zsh

# Purpose: creates a directory with files from the template directory
#
# Arguments: exactly one argument, the name of the new library

if [ "$#" -ne 1 ]; then
	echo " "       >&2
	echo " Usage:" >&2
	echo " "       >&2
	echo  " $0 libraryName"  >&2
	echo " "       >&2
	exit 1
fi


library=$1
echo " "
echo " Creating glibrary" $library
mkdir -p $library


echo " "
for f in SConstruct SConscript example.cc settings.xcconfig README.md
do
	echo " "copying $f
	cp templateGLibrary/$f $library/
done

echo " "
for f in changelog todo
do
	echo " "touching $f
	rm $library/$f
	touch $library/$f
done

cheader=$(echo $library"_h" | tr "[:lower:]" "[:upper:]")
echo " "
echo " "Creating $library header using $cheader

rm $library/$library".h" ; touch $library/$library".h"

echo "#ifndef " $cheader      >> $library/$library".h"
echo "#define " $cheader " 1" >> $library/$library".h"
echo                          >> $library/$library".h"
echo                          >> $library/$library".h"
echo "class $library"         >> $library/$library".h"
echo "{"                      >> $library/$library".h"
echo                          >> $library/$library".h"
echo                          >> $library/$library".h"
echo  "};"                    >> $library/$library".h"
echo                          >> $library/$library".h"
echo                          >> $library/$library".h"
echo "#endif"                 >> $library/$library".h"

echo " "
echo " "Creating $library source
rm $library/$library".cc"; touch $library/$library".cc"

echo "// $library "             >> $library/$library".cc"
echo '#include "'$library'.h"'  >> $library/$library".cc"


echo " "
echo " "Changing template name to $library in:
echo " "
for f in SConstruct SConscript example.cc README.md
do
	echo " "$f
	sed -i '' s/templateGLibrary/$library/g     $library/$f
done

./createDoxyFile $library

echo " "
