#!/bin/bash

doxygen --version

libraries='goptions gfields'

echo " "
for l in $libraries
do
	echo " "Creating $l documentation
	cd $l
	doxygen Doxyfile
	mv $l/html/* $l
	rm -rf $l/html
	cd ..
done
echo " "
