#!/bin/bash

# Purpose: creates the doxygen documentation for all the glibraries
# This script is used by TRAVIS
#
# Arguments: none

echo " "
echo " Doxygen version: "$(doxygen --version)
echo " "
ddir='doxygen'

libraries='goptions gstring gfactory'

if [ -d $ddir ]
then
	rm -rf $ddir
fi
mkdir -p $ddir

# for documentation purposes
ls -l

echo " "
for l in $libraries
do
	./createDoxyfile 
	./makeDoxyfileForLibrary $l
	cd $l
	ls -l
	doxygen Doxyfile 
	mv html ../$ddir/$l
	cd ..
done
echo " "
