#!/bin/bash

echo " "
echo " Doxygen version: "$(doxygen --version)
echo " "
ddir='doxygen'

libraries='goptions gfields'

if [ -d $ddir ]
then
	rm -rf $ddir
fi
mkdir -p $ddir

echo " "
for l in $libraries
do
	echo " "Creating $l documentation
	cd $l
	doxygen Doxyfile
	mv html ../$ddir/$l
	cd ..
done
echo " "
