#!/bin/bash

# Purpose: creates a doxyfile the template doxyfile
# (later: directly from the doxygen -g command to get the latest doxygen goodies)
#
# Arguments: exactly one argument, the name of the new library

if [ "$#" -ne 1 ]; then
	echo " "       >&2
	echo " Usage:" >&2
	echo " "       >&2
	echo  " $0 libraryName"  >&2
	echo " "       >&2
	exit 1
fi


library=$1
echo " Setting Doxyfile for " $library


# replacing instances of "templateGLibrary"
extraArgument=''
case `uname` in
	Darwin)
		extraArgument='backup'
	;;
	Linux)
		extraArgument=''
	;;
esac

sed -i $extraArgument s/templateGLibrary/$library/g Doxyfile # name



if [ $library != "gemc" ]; then
	sed -i $extraArgument 's/HTML_EXTRA_STYLESHEET  =/HTML_EXTRA_STYLESHEET  = ..\/docs\/mylayout.css/g'             Doxyfile
else
	sed -i $extraArgument 's/HTML_EXTRA_STYLESHEET  =/HTML_EXTRA_STYLESHEET  = "glibrary\/docs\/mylayout.css"/g'    Doxyfile
	sed -i $extraArgument 's/PROJECT_BRIEF          =/PROJECT_BRIEF          = "GEMC: GEant4 Monte-Carlo"/g'        Doxyfile
fi
cp Doxyfile $library/
echo " "


echo
echo
echo DOXYFILE:
cat $library/Doxyfile
echo
echo


rm -f Doxyfilebackup
