# This can be called from the local SConstruct or
# the glibrary SConstruct one dir up
from init_env import init_environment

sources = Split("""
	fields.cc
	""")

env = init_environment("")

# destination library is one dir up
lib = env.Library(source = sources, target = "../lib/fields")
