#ifndef  GPARTICLE_H_CONVENTIONS
#define  GPARTICLE_H_CONVENTIONS 1

#define GPARTICLENOTDEFINED -999

// error codes in the 900s
#define EC__GGPARTICLENOTFOUND        901
#define EC__GGPARTICLEWRONGTHETAMODEL 902


#endif
