# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')

sources = [
			  'gstring.cc'
			  ]

# destination library is one dir up - relative to this SConscript
env.Library(source = sources, target = '../lib/gstring')
