# This compiles the example and the gstring library (if it's not built already)

from init_env import init_environment

# load glibraries
env = init_environment("glibrary clhep")
env.Append(CXXFLAGS=['-std=c++17'])

# manually appending this library so the example can be compiled
# the environment above will not pre-load gstring unless it's there already
env.Append(LIBS = 'gstring')

# calling SConscript here to build just the library as in the hierarchy build
lib = SConscript('SConscript', exports='env')

# builds the example
example = env.Program(source = "example.cc", target = "example")

Depends(example,  lib);
