# This can be called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')

sources = [
			  'gstreamer.cc',
			  'gstreamerOptions.cc'
			  ]

# destination library is one dir up - relative to this SConscript
lib = env.Library(source = sources, target='gstreamer')
env.Install('../lib', lib)
