# This compiles the example(s) and the library

from init_env import init_environment

# load glibraries
env = init_environment("glibrary")
env.Append(CXXFLAGS=['-std=c++17'])

# manually appending this library so the example can be compiled
# the environment above will not load goptions if it's not there
env.Append(LIBS = 'goptions')

# calling SConscript here to build just the library as in the hierarchy build
lib = SConscript('SConscript', exports='env')

# builds the example(s)
simpleExample     = env.Program(source = "examples/simpleExample.cc",     target = "simpleExample")
structuredExample = env.Program(source = "examples/structuredExample.cc", target = "structuredExample")

Depends(simpleExample,     lib);
Depends(structuredExample, simpleExample);
