# Importing env from calling script
Import('env')

sources = Split("""
	goption.cc
	goptions.cc
	""")

# destination library is one dir up
lib = env.Library(source = sources, target = "../lib/goptions")
