# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')

sources = [
			  'gsplash.cc',
			  'goptions.cc'
			  ]

# destination library is one dir up - relative to this SConscript
lib = env.Library(source = sources, target = '../lib/goptions')
