# This compiles the example and the goptions library (if it's not built already)

from init_env import init_environment

# load glibraries
env = init_environment("glibrary")

# manually appending this library so the example can be compiled
# the environment above will not load goptions if it's not there
env.Append(LIBS = 'goptions')

# calling SConscript here to build just the library as in the hierarchy build
lib = SConscript('SConscript', exports='env')

# builds the example
example  = env.Program(source = "example.cc",     target = "example")
exampleJ = env.Program(source = "jsonExample.cc", target = "jsonExample")

Depends(example,  lib);
