# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')

sources = [
			  'gQtButtonsWidget.cc',
			  'exampleResources.qrc'
			  ]

# destination library is one dir up - relative to this SConscript
lib = env.Library(source = sources, target = '../lib/gQtButtonsWidget')

