#ifndef  G4VOLUMESCONVENTIONS_H
#define  G4VOLUMESCONVENTIONS_H 1



#define G4SYSTEMNOTAPPLICABLEENTRY  "na"
#define G4SYSTEMLOGHEADER           " ⌂ G4System ▸ "

#define G4SYSTEMNATFACTORY "G4SystemNATVFactory"
#define G4SYSTEMCADFACTORY "G4SystemCADFactory"
#define G4SYSTEMGDMFACTORY "G4SystemGDMLFactory"

// error codes in the 500s
#define EC__G4DEPENDENCIESNOTSOLVED   501
#define EC__G4WRONGORDEREDROTATION    502
#define EC__G4PARAMETERSMISMATCH      503
#define EC__G4SYSTEMFACTORYNOTFOUND   504
#define EC__G4MATERIALNOTFOUND        505

#endif

