# This compiles the example(s) and the library
from init_env import init_environment

# load needed environment for this library
env = init_environment('glibrary')
env.Append(CXXFLAGS=['-std=c++17'])

# we build the library in ../lib
# by default, targets outside the current tree are not selected.
env.Default('../')

# build the library
lib = SConscript('SConscript', exports='env')

