# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')

sources = [
			  'g4volume.cc',
			  'g4system.cc',
			  'g4world.cc'
			  ]

# destination library is one dir up - relative to this SConscript
env.Library(source = sources, target = '../lib/g4system')
