# This can be called from the local SConstruct or
# the glibrary SConstruct one dir up
from init_env import init_environment

env = init_environment("glibrary")

sources = Split("""
	gtouchable.cc
	""")

# destination library is one dir up
lib = env.Library(source = sources, target = "../lib/gtouchable")
