# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')

sources = [
			  'gtron.cc',
			  'gtouchable.cc'
			  ]

# destination library is one dir up - relative to this SConscript
lib = env.Library(source = sources, target='gtouchable')
env.Install('../lib', lib)
