# This can be called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')

sources = Split("""
	gsplash.cc
	exampleResources.qrc
	""")

# destination library is one dir up
lib = env.Library(source = sources, target = "../lib/gsplash")
