# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')

sources = [
			  'templateGLibrary.cc'
			  ]

# destination library is one dir up - relative to this SConscript
# this will ensure that the main glibrary SConstructs aknowledge the
# templateGLibrary object as 'install' instead of just the library build
lib = env.Library(source = sources, target='templateGLibrary')
env.Install('../lib', lib)
