#ifndef  G4DISPLAY_H_CONVENTIONS
#define  G4DISPLAY_H_CONVENTIONS 1

#define GDEFAULTVIEWERDRIVER "OGL"
#define GDEFAULTVIEWERSIZE   "800x800"
#define GDEFAULTVIEWERPOS    "+400+100"


extern std::vector<std::string> AVAILABLEG4VIEWERS;

#endif
