# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')

sources = [
			  'g4displayOptions.cc',
			  'g4display.cc',
			  'g4controls.cc',
			  'tabs/gcamera.cc',
			  'tabs/gslice.cc'
			  ]

# destination library is one dir up - relative to this SConscript
lib = env.Library(source = sources, target='g4display')
env.Install('../lib', lib)
