# This compiles the example(s) and the library
from init_env import init_environment

# load needed environment for this library
env = init_environment('glibrary clhep geant4')
env.Append(CXXFLAGS=['-std=c++17'])

# we build the library in ../lib
# by default, targets outside the current tree are not selected.
env.Default('../')

# build the library
lib = SConscript('SConscript', exports='env')


ctof_dll  = env.SharedLibrary( source = "ctofRoutinesExample.cc",  target = "ctofRoutinesExample")
Depends(ctof_dll,  lib);


example_sources = Split("""
	example.cc
	""")
example = env.Program(source = example_sources, target = "example")

Depends(example,  ctof_dll);
