#ifndef  GDATA_H_CONVENTIONS
#define  GDATA_H_CONVENTIONS 1

// Done this way, the max number of variable / type is 100
#define GMULTIPLIER 100
#define GSTARTINDEX 1
#define GINTINDEXMULTIPLIER GSTARTINDEX
#define GFLOINDEXMULTIPLIER GSTARTINDEX*GMULTIPLIER
#define GDBLINDEXMULTIPLIER GSTARTINDEX*GMULTIPLIER*GMULTIPLIER
#define GSTRINDEXMULTIPLIER GSTARTINDEX*GMULTIPLIER*GMULTIPLIER*GMULTIPLIER

#endif
