# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')

sources = [
			  'gdata.cc',
			  'gobservables/gobservables.cc'
			  ]

# destination library is one dir up - relative to this SConscript
lib = env.Library(source = sources, target = '../lib/gdata')

