# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')

# local directories include
env.Append(CPPPATH = [Dir('event')])

sources = [
			  'gDataCollection.cc',
			  'event/gEventDataCollection.cc',
			  'event/gEventDataCollectionHeader.cc',
			  'gDigitizedData.cc',
			  'gTrueInfoData.cc'
			  ]

# destination library is one dir up - relative to this SConscript
lib = env.Library(source = sources, target = '../lib/gdata')

