# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')

env.Append(CPPPATH = [Dir('gsystemFactories'), Dir('gsystemFactories/cad'), Dir('gsystemFactories/text'), Dir('gsystemFactories/gdml'), Dir('gsystemFactories/mysql')])

sources = [
			  'gvolume.cc',
			  'gmaterial.cc',
			  'gsystem.cc',
			  'gworld.cc',
			  'gsystemOptions.cc',
			  'gsystemFactories/text/systemTextFactory.cc',
			  'gsystemFactories/text/loadMaterial.cc',
			  'gsystemFactories/text/loadGeometry.cc',
			  'gsystemFactories/cad/systemCadFactory.cc',
			  'gsystemFactories/cad/loadMaterial.cc',
			  'gsystemFactories/cad/loadGeometry.cc',
			  'gsystemFactories/gdml/systemGdmlFactory.cc',
			  'gsystemFactories/gdml/loadMaterial.cc',
			  'gsystemFactories/gdml/loadGeometry.cc'
			  ]

# destination library is one dir up - relative to this SConscript
lib = env.Library(source = sources, target='../lib/gsystem')
